const { chromium } = require('playwright');
const path = require('node:path');

(async () => {
  const browser = await chromium.launch({ headless: true, executablePath: 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe' });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 }, deviceScaleFactor: 1 });
  const errors = [];
  page.on('console', message => { if (message.type() === 'error') errors.push(`console: ${message.text()}`); });
  page.on('pageerror', error => errors.push(`page: ${error.message}`));
  page.on('requestfailed', request => errors.push(`request: ${request.url()} ${request.failure()?.errorText || ''}`));
  await page.goto('http://127.0.0.1:4187/', { waitUntil: 'networkidle' });
  await page.locator('input[name="participantName"]').fill('Диана');
  await page.getByRole('button', { name: '+ Добавить', exact: true }).click();
  await page.getByRole('button', { name: '+ Добавить', exact: true }).click();
  const names = page.locator('input[name="participantName"]');
  await names.nth(1).fill('Альмира');
  await names.nth(2).fill('Ирина');
  await page.getByRole('button', { name: 'Начать партию', exact: true }).click();
  await page.getByText('Инструменты ведущей', { exact: true }).click();
  await page.locator('#position-value').fill('8');
  await page.getByRole('button', { name: 'Исправить позицию', exact: true }).click();
  await page.getByRole('button', { name: 'Добавить жетон', exact: true }).first().click();
  await page.getByLabel('Исходный запрос', { exact: true }).fill('Понять следующий профессиональный шаг');
  await page.getByRole('button', { name: 'Бросить кубик', exact: true }).click();
  await page.locator('#card-modal').waitFor({ state: 'visible' });
  await page.locator('#card-image').evaluate(img => img.complete && img.naturalWidth > 0);
  await page.screenshot({ path: path.resolve('screenshots/desktop.png'), fullPage: false });
  await page.getByRole('button', { name: 'Подтвердить и продолжить', exact: true }).click();
  await page.reload({ waitUntil: 'networkidle' });
  await page.getByRole('button', { name: 'Продолжить игру', exact: true }).click();
  const restored = await page.locator('#players-list').innerText();
  if (!restored.includes('Диана') || !restored.includes('Альмира') || !restored.includes('Ирина')) throw new Error('Состояние не восстановилось после обновления.');
  await page.setViewportSize({ width: 390, height: 1200 });
  await page.waitForTimeout(300);
  const noHorizontalOverflow = await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth);
  await page.screenshot({ path: path.resolve('screenshots/mobile.png'), fullPage: false });
  console.log(JSON.stringify({ restored: true, noHorizontalOverflow, errors }, null, 2));
  await browser.close();
  if (!noHorizontalOverflow || errors.length) process.exitCode = 1;
})().catch(error => { console.error(error); process.exitCode = 1; });
